# Generated by Django 2.2.7 on 2019-12-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191202_1630'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='profile',
        ),
    ]
