# Generated by Django 2.2.7 on 2019-12-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191204_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image3d',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
